"""API SQLite Database Layer.

Exports connection, schema management, and DAO repositories.
"""
from api.db.connection import (
    _SCHEMA,
    _COLUMN_MIGRATIONS,
    _INITIALIZED_DB_PATHS,
    _INIT_LOCK,
    _migrate_columns,
    _migrate_dispatcher_column_cards,
    _backfill_kanban_display_seq,
    init_schema,
    get_connection,
)
from api.db.uow import DbUnitOfWork
from api.db.repositories.job_repository import (
    create_job,
    set_job_awaiting_approval,
    set_job_resume_value,
    claim_job_resume,
    clear_job_resume_value,
    find_job_by_idempotency_key,
    get_job,
    update_job_status,
    cas_job_status,
    list_jobs_by_status,
    append_job_log,
    get_job_logs_since,
    get_job_reply_logs,
    get_latest_job_log_node,
    get_job_log_count,
)
from api.db.repositories.kanban_repository import (
    list_kanban_cards,
    create_kanban_card,
    create_parking_lot_cards,
    update_kanban_card,
    set_kanban_card_source,
    toggle_kanban_card_discord,
    mark_discord_events_sent,
    move_kanban_card,
    get_kanban_card,
    find_kanban_card_by_title_in_column,
    delete_kanban_card,
)
from api.db.repositories.dcf_repository import (
    record_dcf_evaluation,
    get_latest_dcf_evaluation,
    get_dcf_evaluation_by_id,
)
from api.db.repositories.insider_repository import (
    record_sec_form4_filing,
    record_sec_insider_transaction,
    get_sec_insider_filings_and_transactions,
)
from api.db.repositories.cache_repository import (
    get_analyst_context_cache,
    upsert_analyst_context_cache,
    get_financial_statements_cache,
    get_raw_financial_statements_cache,
    upsert_financial_statements_cache,
)
from api.db.repositories.outbox_repository import (
    enqueue_event,
    get_event,
    list_pending,
    mark_sent,
    mark_failed,
)

__all__ = [
    "_SCHEMA",
    "_COLUMN_MIGRATIONS",
    "_INITIALIZED_DB_PATHS",
    "_INIT_LOCK",
    "_migrate_columns",
    "_migrate_dispatcher_column_cards",
    "_backfill_kanban_display_seq",
    "init_schema",
    "get_connection",
    "create_job",
    "set_job_awaiting_approval",
    "set_job_resume_value",
    "claim_job_resume",
    "clear_job_resume_value",
    "find_job_by_idempotency_key",
    "get_job",
    "update_job_status",
    "cas_job_status",
    "list_jobs_by_status",
    "append_job_log",
    "get_job_logs_since",
    "get_job_reply_logs",
    "get_latest_job_log_node",
    "get_job_log_count",
    "list_kanban_cards",
    "create_kanban_card",
    "create_parking_lot_cards",
    "update_kanban_card",
    "set_kanban_card_source",
    "toggle_kanban_card_discord",
    "mark_discord_events_sent",
    "move_kanban_card",
    "get_kanban_card",
    "find_kanban_card_by_title_in_column",
    "delete_kanban_card",
    "record_dcf_evaluation",
    "get_latest_dcf_evaluation",
    "get_dcf_evaluation_by_id",
    "record_sec_form4_filing",
    "record_sec_insider_transaction",
    "get_sec_insider_filings_and_transactions",
    "get_analyst_context_cache",
    "upsert_analyst_context_cache",
    "get_financial_statements_cache",
    "get_raw_financial_statements_cache",
    "upsert_financial_statements_cache",
    "enqueue_event",
    "get_event",
    "list_pending",
    "mark_sent",
    "mark_failed",
]
