"""Financial Domain Constants and Concept Synonyms."""
from typing import Any

CANONICAL_LINE_ITEMS: dict[str, list[dict[str, Any]]] = {
    "income": [
        {"key": "revenue", "label": "Revenue / Total Sales", "unit_type": "currency", "is_primary": True},
        {"key": "cost_of_revenue", "label": "Cost of Goods Sold (COGS)", "unit_type": "currency", "is_primary": False},
        {"key": "gross_profit", "label": "Gross Profit", "unit_type": "currency", "is_primary": True},
        {"key": "research_and_development", "label": "Research & Development (R&D)", "unit_type": "currency", "is_primary": False},
        {"key": "sales_and_marketing", "label": "Sales & Marketing", "unit_type": "currency", "is_primary": False},
        {"key": "general_and_administrative", "label": "General & Administrative", "unit_type": "currency", "is_primary": False},
        {"key": "selling_general_admin", "label": "SG&A Expenses (Combined)", "unit_type": "currency", "is_primary": False},
        {"key": "operating_expenses", "label": "Total Operating Expenses", "unit_type": "currency", "is_primary": False},
        {"key": "operating_income", "label": "Operating Income (EBIT)", "unit_type": "currency", "is_primary": True},
        {"key": "net_income", "label": "Net Income", "unit_type": "currency", "is_primary": True},
        {"key": "eps_basic", "label": "Basic EPS", "unit_type": "per_share", "is_primary": False},
        {"key": "eps_diluted", "label": "Diluted EPS", "unit_type": "per_share", "is_primary": True},
    ],
    "balance_sheet": [
        {"key": "cash_and_equivalents", "label": "Cash & Cash Equivalents", "unit_type": "currency", "is_primary": True},
        {"key": "short_term_investments", "label": "Short-Term Investments", "unit_type": "currency", "is_primary": False},
        {"key": "accounts_receivable", "label": "Accounts Receivable", "unit_type": "currency", "is_primary": False},
        {"key": "inventory", "label": "Inventory", "unit_type": "currency", "is_primary": False},
        {"key": "deferred_contract_costs", "label": "Deferred Contract Costs", "unit_type": "currency", "is_primary": False},
        {"key": "current_assets", "label": "Total Current Assets", "unit_type": "currency", "is_primary": True},
        {"key": "property_plant_equipment", "label": "Property, Plant & Equipment (Net)", "unit_type": "currency", "is_primary": False},
        {"key": "long_term_investments", "label": "Long-Term Investments", "unit_type": "currency", "is_primary": False},
        {"key": "goodwill", "label": "Goodwill", "unit_type": "currency", "is_primary": False},
        {"key": "other_intangible_assets", "label": "Other Intangible Assets (Net)", "unit_type": "currency", "is_primary": False},
        {"key": "deferred_tax_assets", "label": "Deferred Tax Assets", "unit_type": "currency", "is_primary": False},
        {"key": "total_assets", "label": "Total Assets", "unit_type": "currency", "is_primary": True},
        {"key": "accounts_payable", "label": "Accounts Payable", "unit_type": "currency", "is_primary": False},
        {"key": "short_term_debt", "label": "Short-Term Debt", "unit_type": "currency", "is_primary": False},
        {"key": "deferred_revenue_current", "label": "Deferred Revenue (Current)", "unit_type": "currency", "is_primary": False},
        {"key": "income_tax_liabilities", "label": "Income Tax Liabilities", "unit_type": "currency", "is_primary": False},
        {"key": "current_liabilities", "label": "Total Current Liabilities", "unit_type": "currency", "is_primary": True},
        {"key": "long_term_debt", "label": "Long-Term Debt", "unit_type": "currency", "is_primary": False},
        {"key": "deferred_revenue_noncurrent", "label": "Deferred Revenue (Non-Current)", "unit_type": "currency", "is_primary": False},
        {"key": "total_debt", "label": "Total Debt", "unit_type": "currency", "is_primary": True},
        {"key": "total_liabilities", "label": "Total Liabilities", "unit_type": "currency", "is_primary": True},
        {"key": "stockholders_equity", "label": "Total Stockholders' Equity", "unit_type": "currency", "is_primary": True},
        {"key": "noncontrolling_interests", "label": "Non-controlling Interests", "unit_type": "currency", "is_primary": False},
        {"key": "total_equity", "label": "Total Equity", "unit_type": "currency", "is_primary": True},
    ],
    "cash_flow": [
        {"key": "operating_cash_flow", "label": "Cash Flow from Operating Activities", "unit_type": "currency", "is_primary": True},
        {"key": "capital_expenditure", "label": "Capital Expenditures (CapEx)", "unit_type": "currency", "is_primary": False},
        {"key": "calculated_free_cash_flow", "label": "Calculated Free Cash Flow (OCF - |CapEx|)", "unit_type": "currency", "is_primary": True},
        {"key": "reported_free_cash_flow", "label": "Company-Reported FCF (Non-GAAP)", "unit_type": "currency", "is_primary": False},
        {"key": "free_cash_flow_adjustments", "label": "FCF Disclosed Adjustments", "unit_type": "currency", "is_primary": False},
        {"key": "free_cash_flow", "label": "Free Cash Flow (FCF)", "unit_type": "currency", "is_primary": False},
        {"key": "investing_cash_flow", "label": "Cash Flow from Investing Activities", "unit_type": "currency", "is_primary": False},
        {"key": "financing_cash_flow", "label": "Cash Flow from Financing Activities", "unit_type": "currency", "is_primary": False},
        {"key": "net_change_in_cash", "label": "Net Change in Cash", "unit_type": "currency", "is_primary": False},
    ],
}

EDGAR_CONCEPT_SYNONYMS: dict[str, list[str]] = {
    "revenue": ["RevenueFromContractWithCustomerExcludingAssessedTax", "SalesRevenueNet", "RevenueFromContractWithCustomerIncludingAssessedTax", "Revenues", "Revenue"],
    "cost_of_revenue": ["CostOfGoodsAndServicesSold", "CostOfRevenue", "CostOfGoodsSold"],
    "gross_profit": ["GrossProfit"],
    "research_and_development": ["ResearchAndDevelopmentExpense", "ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost"],
    "sales_and_marketing": ["SellingAndMarketingExpense", "SellingExpense"],
    "general_and_administrative": ["GeneralAndAdministrativeExpense"],
    "selling_general_admin": ["SellingGeneralAndAdministrativeExpense"],
    "operating_expenses": ["OperatingExpenses", "CostsAndExpenses"],
    "operating_income": ["OperatingIncomeLoss"],
    "net_income": ["NetIncomeLoss", "ProfitLoss"],
    "eps_basic": ["EarningsPerShareBasic"],
    "eps_diluted": ["EarningsPerShareDiluted"],
    "cash_and_equivalents": ["CashAndCashEquivalentsAtCarryingValue", "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents", "CashAndCashEquivalents"],
    "short_term_investments": ["OtherShortTermInvestments", "ShortTermInvestments", "MarketableSecuritiesCurrent", "AvailableForSaleSecuritiesCurrent"],
    "accounts_receivable": ["AccountsReceivableNetCurrent"],
    "inventory": ["InventoryNet", "InventoryGross"],
    "current_assets": ["AssetsCurrent"],
    "property_plant_equipment": ["PropertyPlantAndEquipmentNet"],
    "total_assets": ["Assets"],
    "accounts_payable": ["AccountsPayableCurrent"],
    "short_term_debt": ["LongTermDebtCurrent", "ShortTermBorrowings", "DebtCurrent", "CommercialPaper"],
    "current_liabilities": ["LiabilitiesCurrent"],
    "long_term_debt": ["LongTermDebtNoncurrent", "LongTermDebtAndCapitalLeaseObligations"],
    "total_debt": ["DebtAndCapitalLeaseObligations", "TotalDebt"],
    "total_liabilities": ["Liabilities"],
    "stockholders_equity": ["StockholdersEquity", "CommonStockholdersEquity"],
    "noncontrolling_interests": ["MinorityInterest", "NoncontrollingInterestInSubsidiaryParent", "MinorityInterestInSusidiaries", "NoncontrollingInterest"],
    "total_equity": ["StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest", "TotalEquity"],
    "deferred_revenue_current": ["ContractWithCustomerLiabilityCurrent", "DeferredRevenueCurrent", "DeferredRevenueAndCreditsCurrent"],
    "deferred_revenue_noncurrent": ["ContractWithCustomerLiabilityNoncurrent", "DeferredRevenueNoncurrent", "DeferredRevenueAndCreditsNoncurrent"],
    "income_tax_liabilities": ["AccruedIncomeTaxesCurrent", "IncomeTaxesPayableCurrent", "AccruedIncomeTaxesNoncurrent", "IncomeTaxesPayableNoncurrent", "IncomeTaxPayable", "AccruedIncomeTaxes"],
    "long_term_investments": ["LongTermInvestments", "MarketableSecuritiesNoncurrent", "AvailableForSaleSecuritiesNoncurrent", "HeldToMaturitySecuritiesNoncurrent", "OtherLongTermInvestments", "OtherInvestmentsNoncurrent"],
    "deferred_contract_costs": ["DeferredContractCostNet", "DeferredContractCost", "DeferredContractCosts", "ContractWithCustomerAsset", "ContractWithCustomerAssetNet", "DeferredContractAcquisitionCostNet", "DeferredContractAcquisitionCosts"],
    "deferred_contract_costs_current": ["DeferredContractCostCurrent", "DeferredContractCostsCurrent", "DeferredContractAcquisitionCostsCurrent", "ContractWithCustomerAssetCurrent"],
    "deferred_contract_costs_noncurrent": ["DeferredContractCostNoncurrent", "DeferredContractCostsNoncurrent", "DeferredContractAcquisitionCostsNoncurrent", "ContractWithCustomerAssetNoncurrent"],
    "deferred_tax_assets": ["DeferredIncomeTaxAssetsNet", "DeferredTaxAssetsNetNoncurrent", "DeferredTaxAssetsNetCurrent", "DeferredTaxAssetsLiabilitiesNet"],
    "goodwill": ["Goodwill"],
    "other_intangible_assets": ["IntangibleAssetsNetExcludingGoodwill", "FiniteLivedIntangibleAssetsNet", "OtherIntangibleAssetsNet", "IndefiniteLivedIntangibleAssetsExcludingGoodwill", "IntangibleAssetsNet"],
    "operating_cash_flow": ["NetCashProvidedByUsedInOperatingActivities"],
    "capital_expenditure": ["PaymentsToAcquirePropertyPlantAndEquipment", "PaymentsToAcquireProductiveAssets"],
    "investing_cash_flow": ["NetCashProvidedByUsedInInvestingActivities"],
    "financing_cash_flow": ["NetCashProvidedByUsedInFinancingActivities"],
    "net_change_in_cash": ["CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect"],
}

YFINANCE_CONCEPT_MAP: dict[str, list[str]] = {
    "revenue": ["Total Revenue", "Operating Revenue", "Revenue"],
    "cost_of_revenue": ["Cost Of Revenue", "Cost of Goods Sold"],
    "gross_profit": ["Gross Profit"],
    "research_and_development": ["Research And Development", "Research & Development"],
    "sales_and_marketing": ["Selling And Marketing Expense", "Selling & Marketing"],
    "general_and_administrative": ["General And Administrative Expense", "General & Administrative"],
    "selling_general_admin": ["Selling General And Administration", "SG&A"],
    "operating_expenses": ["Operating Expense", "Total Expenses"],
    "operating_income": ["Operating Income", "EBIT"],
    "net_income": ["Net Income", "Net Income Common Stockholders"],
    "eps_basic": ["Basic EPS"],
    "eps_diluted": ["Diluted EPS"],
    "cash_and_equivalents": ["Cash And Cash Equivalents", "Cash Cash Equivalents And Short Term Investments"],
    "short_term_investments": ["Other Short Term Investments", "Short Term Investments"],
    "accounts_receivable": ["Receivables", "Accounts Receivable"],
    "inventory": ["Inventory"],
    "current_assets": ["Current Assets"],
    "property_plant_equipment": ["Net PPE", "Gross PPE", "Property Plant Equipment"],
    "total_assets": ["Total Assets"],
    "accounts_payable": ["Accounts Payable", "Payables"],
    "short_term_debt": ["Current Debt", "Commercial Paper"],
    "current_liabilities": ["Current Liabilities"],
    "long_term_debt": ["Long Term Debt"],
    "total_debt": ["Total Debt"],
    "total_liabilities": ["Total Liabilities Net Minority Interest", "Total Liabilities"],
    "stockholders_equity": ["Stockholders Equity", "Common Stock Equity"],
    "noncontrolling_interests": ["Minority Interest", "Non Controlling Interest"],
    "total_equity": ["Total Equity Gross Minority Interest", "Total Equity"],
    "deferred_revenue_current": ["Current Deferred Revenue", "Deferred Revenue"],
    "deferred_revenue_noncurrent": ["Non Current Deferred Revenue", "Non-Current Deferred Revenue"],
    "income_tax_liabilities": ["Income Tax Payable", "Taxes Payable"],
    "long_term_investments": ["Long Term Investments", "Investment in Financial Assets"],
    "deferred_contract_costs": ["Deferred Contract Costs"],
    "deferred_tax_assets": ["Deferred Tax Assets"],
    "goodwill": ["Goodwill"],
    "other_intangible_assets": ["Other Intangible Assets"],
    "operating_cash_flow": ["Operating Cash Flow", "Cash Flow From Continuing Operating Activities"],
    "capital_expenditure": ["Capital Expenditure", "Purchase Of PPE"],
    "investing_cash_flow": ["Investing Cash Flow", "Cash Flow From Continuing Investing Activities"],
    "financing_cash_flow": ["Financing Cash Flow", "Cash Flow From Continuing Financing Activities"],
    "net_change_in_cash": ["Changes In Cash", "Change In Cash"],
}

REQUIRED_CORE_FIELDS: dict[str, list[str]] = {
    "income": ["revenue", "gross_profit", "operating_income", "net_income", "eps_diluted"],
    "balance_sheet": ["cash_and_equivalents", "current_assets", "current_liabilities", "total_assets", "total_liabilities", "total_equity"],
    "cash_flow": ["operating_cash_flow", "capital_expenditure", "calculated_free_cash_flow"],
}

REQUIRED_EXPANDED_FIELDS: dict[str, list[str]] = {
    "balance_sheet": [
        "long_term_investments",
        "deferred_contract_costs",
        "deferred_tax_assets",
        "goodwill",
        "other_intangible_assets",
        "deferred_revenue_current",
        "income_tax_liabilities",
        "noncontrolling_interests",
    ],
    "cash_flow": [
        "reported_free_cash_flow",
        "free_cash_flow_adjustments",
    ],
}
