"""Typed Data Transfer Objects (DTO) for Investor Essence Application Layer.

These are pure dataclasses with NO frameworks, NO FastAPI, and NO Pydantic:
- Immutable command, query, and presentation view objects
- External LLM generation proposals
- Portfolio planning and apply snapshots/receipts
"""
from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class ContentOptionProposal:
    key: str
    text: str


@dataclass(frozen=True)
class QuestionProposal:
    """Proposal generated by LLM for next adaptive question."""
    text: str
    options: List[ContentOptionProposal]
    coverage_topics: List[str]
    evidence_type: str
    is_clarification: bool = False


@dataclass(frozen=True)
class EvidenceSnapshot:
    """Frozen input context of prior Q&A passed to LLM."""
    session_id: str
    branch_id: str
    revision: int
    context_hash: str
    qa_pairs: List[Dict[str, Any]]
    coverage_topics: List[str]


@dataclass(frozen=True)
class ClaimProposal:
    text: str
    source_kind: str
    supporting_question_ids: List[str]
    quote: str
    evidence_type: str


@dataclass(frozen=True)
class EssenceSummaryProposal:
    """Proposal generated by LLM for essence summary."""
    statement: str
    claims: List[ClaimProposal]
    unresolved_topics: List[str]
    coverage_report: List[Dict[str, Any]]


@dataclass(frozen=True)
class NumericPolicyFieldDTO:
    field_id: str
    value: Optional[str]
    unit: str
    calculation_basis: str
    origin: str
    source_refs: List[str] = field(default_factory=list)
    assumptions: str = ""
    is_confirmed: bool = False


@dataclass(frozen=True)
class AllocationRowDTO:
    allocation_id: str
    category_name: str
    target_percent: str
    role_description: str


@dataclass(frozen=True)
class AxisProposal:
    """Proposal generated by LLM for 8-section investment axis."""
    basic_policy: str
    risk_limits: Dict[str, NumericPolicyFieldDTO]
    invest_targets: List[str]
    exclude_targets: List[str]
    primary_methods: List[str]
    secondary_methods: List[str]
    investment_horizon: str
    allocation_basis: str
    allocation_rows: List[AllocationRowDTO]
    rebalance_frequency: str
    role_models: List[str]
    non_actions: List[str]
    assumptions: List[str] = field(default_factory=list)
    clarifications: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class PurposeBucketProposal:
    name: str
    role: str
    color: str
    target_percent: str
    bucket_id: Optional[str] = None
    source_value_ids: List[str] = field(default_factory=list)
    source_axis_allocation_ids: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class BucketPlanProposal:
    purpose_buckets: List[PurposeBucketProposal]
    allocation_basis: str
    mapping_weights: List[Dict[str, Any]]
@dataclass(frozen=True)
class WeightedAllocationMappingProposal:
    axis_allocation_id: str
    bucket_id: str
    portfolio_weight_percent: str


# Backward-compatible aliases
NumericPolicyFieldProposal = NumericPolicyFieldDTO
AllocationPlanRowProposal = AllocationRowDTO

class PortfolioPlanningSnapshot:
    """Consistent point-in-time snapshot of portfolio state & checkpoint."""
    portfolio_id: str
    name: str
    checkpoint_sequence: int
    checkpoint_state_hash: str
    base_currency: str
    nav_thb: Decimal
    cash_thb: Decimal
    as_of: str
    targets: List[Dict[str, Any]]
    holdings_summary: List[Dict[str, Any]]


@dataclass(frozen=True)
class PreviewAllocationCommand:
    portfolio_id: str
    expected_checkpoint_sequence: int
    expected_checkpoint_state_hash: str
    target_rows: List[Dict[str, Any]]
    mapping_weights: List[Dict[str, Any]]
    remapping: List[Dict[str, Any]]


@dataclass(frozen=True)
class AllocationPreview:
    checkpoint_sequence: int
    checkpoint_state_hash: str
    validated_targets: List[Dict[str, Any]]
    affected_holdings: List[Dict[str, Any]]
    before_allocation: Dict[str, Any]
    after_allocation: Dict[str, Any]
    issues: List[str]
    payload_hash: str


@dataclass(frozen=True)
class ApplyAllocationCommand:
    command_id: str
    request_hash: str
    portfolio_id: str
    expected_checkpoint_sequence: int
    expected_checkpoint_state_hash: str
    target_rows: List[Dict[str, Any]]
    mapping_weights: List[Dict[str, Any]]
    remapping: List[Dict[str, Any]]
    accepted_policy_snapshot: Dict[str, Any]
    source_refs: Dict[str, str]


@dataclass(frozen=True)
class AllocationApplyReceipt:
    command_id: str
    portfolio_id: str
    request_hash: str
    applied_sequence: int
    applied_state_hash: str
    applied_at_iso: str
    canonical_status: str  # committed | duplicate_reused
    projection_status: str  # ready | pending
    warnings: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class OperationView:
    operation_id: str
    stage: str
    resource_id: str
    resource_revision: int
    status: str  # queued | running | succeeded | superseded | retry_wait | failed
    attempt: int
    poll_url: str
    error_code: Optional[str] = None
    error_message: Optional[str] = None
    retryable: bool = False
    result_ref: Optional[str] = None
    result: Optional[Dict[str, Any]] = None


@dataclass(frozen=True)
class SessionView:
    session_id: str
    status: str
    revision: int
    active_branch_id: str
    questions_count: int
    answers_count: int
    is_complete: bool
    current_question: Optional[Dict[str, Any]] = None
    qa_history: List[Dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True)
class SummaryView:
    summary_id: str
    session_id: str
    statement: str
    claims: List[Dict[str, Any]]
    unresolved_topics: List[str]
    coverage_report: List[Dict[str, Any]]
    revision: int


@dataclass(frozen=True)
class ConfirmationView:
    confirmation_id: str
    status: str  # pending | committed | conflict
    accepted_claims_count: int
    artifact_ref: Optional[Dict[str, str]] = None
    message: str = ""


@dataclass(frozen=True)
class FinancialContextView:
    snapshot_id: str
    portfolio_id: str
    horizon_years: Optional[str] = None
    target_use_amount: Optional[str] = None
    target_use_range: Optional[str] = None
    target_use_timeline: Optional[str] = None
    emergency_reserves_amount: Optional[str] = None
    emergency_reserves_months: Optional[str] = None
    obligations_monthly: Optional[str] = None
    obligations_description: Optional[str] = None
    withdrawal_frequency: Optional[str] = None
    withdrawal_amount: Optional[str] = None
    experience_description: Optional[str] = None
    unknown_fields: List[str] = field(default_factory=list)
    as_of: str = ""
    source: str = "user_reported"
    readiness_issues: List[Dict[str, Any]] = field(default_factory=list)
    is_ready_for_numeric_policy: bool = False


@dataclass(frozen=True)
class AxisDraftView:
    draft_id: str
    portfolio_id: str
    essence_ref: Dict[str, Any]
    context_ref: str
    basic_policy: str
    risk_limits: Dict[str, Any]
    invest_targets: List[str]
    exclude_targets: List[str]
    primary_methods: List[str]
    secondary_methods: List[str]
    investment_horizon: str
    allocation_basis: str
    allocation_rows: List[Dict[str, Any]]
    rebalance_frequency: str
    role_models: List[str]
    non_actions: List[str]
    assumptions: List[str] = field(default_factory=list)
    clarifications: List[str] = field(default_factory=list)
    revision: int = 1
    completeness_issues: List[str] = field(default_factory=list)
    is_complete: bool = False


@dataclass(frozen=True)
class BucketPlanDraftView:
    draft_id: str
    portfolio_id: str
    essence_ref: Dict[str, Any]
    axis_ref: Dict[str, Any]
    context_ref: str
    portfolio_checkpoint: Dict[str, Any]
    purpose_buckets: List[Dict[str, Any]]
    allocation_basis: str
    mapping_weights: List[Dict[str, Any]]
    constraints: List[str]
    remapping: List[Dict[str, Any]]
    status: str
    revision: int
    validation_issues: List[str] = field(default_factory=list)
    is_valid: bool = False

